# Run on master, develop and all feature-branches. More?
trigger:
- master
- develop
- feature/*
pool:
  vmImage: 'ubuntu-latest'

# Build the .Net Core projects
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

# Run any tests present    
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'